# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1d69a66c4302d7c402406993fb59c4025c38036aeb9c570533cffcab5ad80cbc6eeee1d7611fbe5f6791888a3f7160df7db2221ad838a22e1d6e9886aa08829

test:
  secret_key_base: c357ab1254f3bb03e139068bf5d19e9a8879c44e9beb7c7e93ff55d362b29bea2120baebbb8d1226d826f5ecfde3d53d183b100a2f78c7f46bb3c41287afb0a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
